import type { Metadata } from "next";
import { Inter, Kantumruy_Pro } from "next/font/google";
import "./globals.css";
import AuthProvider from "./AuthProvider";
import LayoutWrapper from "./LayoutWrapper";
import ReactQueryProvider from "./ReactQueryProvider";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  display: "swap",
});

const koh = Kantumruy_Pro({
  variable: "--font-koh",
  weight: "500",
  subsets: ["khmer"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable} ${koh.variable}`}>
        <AuthProvider>
          <ReactQueryProvider>
            <LayoutWrapper>{children}</LayoutWrapper>
          </ReactQueryProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
